# Generated by Django 2.2.9 on 2020-02-23 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete='CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete='CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='scheduler.Service')),
            ],
        ),
    ]
