# Generated by Django 2.2.9 on 2020-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecreamflavour',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
