# Generated by Django 2.2.9 on 2020-02-14 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquirer',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='users.Enquirer'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='service',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='scheduler.Service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='scheduler.Service'),
        ),
    ]
