# Generated by Django 2.2.9 on 2020-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200128_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CalendarEvent',
                'verbose_name_plural': 'CalendarEvents',
            },
        ),
        migrations.CreateModel(
            name='Enquirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='enquirer',
            field=models.ForeignKey(on_delete='CASCADE', to='scheduler.Enquirer'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='service',
            field=models.ForeignKey(on_delete='CASCADE', to='scheduler.Service'),
        ),
    ]
