# Generated by Django 2.2.9 on 2020-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20200128_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='appointment', max_length=50),
        ),
    ]
