# Generated by Django 2.2.9 on 2020-02-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_doctorschedulepage_secretaryschedulepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='enquirer',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='scheduler.Enquirer'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='service',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='scheduler.Service'),
        ),
    ]
