# Generated by Django 2.2.9 on 2020-02-09 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('scheduler', '0007_auto_20200208_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickDateTimePage',
            new_name='EnquirePage',
        ),
    ]
